### PR TITLE
Modification to include tau (data space distance)

### PR DESCRIPTION
**Pull request by yonatank93**
I also updated some documentations and tests related to this change.

### CODE REVIEW

**Comment by yonatank93** [comment]
And do we want to bump up the version to 0.1.0 or 1.0.0? Currently it is version 0.0.1.

**Comment by yonatank93** [comment]
For the last commit above, I think it will be useful for other users if we upload this package to Pypi, so they can do `pip install mbam` to install this package. But in case we couldn't do it before the presentation, I removed the documentation about installation via pip so it won't mislead users.

**Comment by mktranstrum** [comment]
Will you please also increment the version number?

**Comment by yonatank93** [comment]
@mktranstrum Would the new version number be 0.1.0 or 1.0.0?

**Comment by mktranstrum** [comment]
0.1.0

**Comment by yonatank93** [comment]
Done. And do we want to upload this package to Pypi too, so other people can do `pip install mbam`?

**Comment by mktranstrum** [comment]
Is there any reason not to include a pip install at this point?

**Comment by yonatank93** [comment]
I haven't uploaded this package to Pypi yet. I want to make sure it works first before doing that and adding `pip install` to README.

**Comment by mktranstrum** [comment]
Please do all the checks before adding pip install.

**Comment by yonatank93** [comment]
Will do. So far this version passes all the tests we have. Is there anything else that I should do?

**Comment by yonatank93** [comment]
@mktranstrum I added test for the parameterspacenorm flag based on your suggestion. I checked that this current version pass all the tests.

**Pull request merged**
